Config:
  DEBUG_WEBSITE: true
  DEBUG_FRAMEWORK: true
  LOG_TYPE: LOG
  CHARSET: utf-8
  DEFAULT_LANG: French
  DEFAULT_RENDER: JSON

Displayers:
  LOG: logger

Render:
  JSON: json
  XML: xml
  PLAIN: txt
  HTML:
    -html
    -htm
    -xhtml

Languages:
  FRENCH: fr
  ENGLISH: en